### ISSUE TITLE
Inifinite recursion when tree object used in RSpec expectations

### ISSUE THREAD

**Issue by jonbrenner** [evolve75/RubyTree#50]
Running this test with RSpec:
```ruby
require "rspec"
require "tree"

describe 'tree' do
  it 'does something' do
    tree = Tree::TreeNode.new("")
    expect(tree).to eq(Object.new)
	end
end
```

Turtles all the way down when the expectation fails:
```bash
➜  treetest  rspec treetest_spec.rb
/Users/jon/.rvm/gems/ruby-2.2.2@treetest/gems/rspec-expectations-3.2.1/lib/rspec/matchers/built_in/eq.rb:35: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
/Users/jon/.rvm/gems/ruby-2.2.2@treetest/gems/rspec-expectations-3.2.1/lib/rspec/matchers/built_in/eq.rb:35: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
F

Failures:

  1) tree does something
     Failure/Error: expect(tree).to eq(Object.new)
     SystemStackError:
       stack level too deep
     # /Users/jon/.rvm/gems/ruby-2.2.2@treetest/gems/rubytree-0.9.6/lib/tree.rb:643:in `each'
     ...recurses into oblivion...
     # /Users/jon/.rvm/gems/ruby-2.2.2@treetest/gems/rubytree-0.9.6/lib/tree.rb:643:in `each'
     # ./treetest_spec.rb:7:in `block (2 levels) in <top (required)>'
```

It behaves normally when the test passes. Interestingly, fails normally when compared to a fixnum. For example, using eq(1) results in a normal test fail.

version info:
```
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

*** LOCAL GEMS ***

bigdecimal (1.2.6)
bundler-unload (1.0.2)
diff-lcs (1.2.5)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
rspec (3.2.0)
rspec-core (3.2.3)
rspec-expectations (3.2.1)
rspec-mocks (3.2.1)
rspec-support (3.2.2)
rubygems-bundler (1.4.4)
rubytree (0.9.6)
rvm (1.11.3.9)
structured_warnings (0.2.0)
test-unit (3.0.8)
```

**Comment by evolve75** [comment]
@jonbrenner,

Apologies for a very late response. I have added a small Rspec suite to the latest release *R0.9.7* (commit db48c35b0a3b96e4da473b095c), but was unable to replicate your issue. I did make an unrelated change to the way the `<=>` operator works, but this should not be the cause.

Hoping that the issue is now resolved for you as well. The Rspec file can be run using `rake spec` from the command line. Please feel free to reopen the issue, if this is still occurring for you.
